### PR TITLE
exynos_format update

### PR DESCRIPTION
**Pull request by Motorhead1991**

### CODE REVIEW

**Comment by bmc08gt** [comment]
The platform is still exynos5, check your build prop. Also I need to verify
this header is needed.

**Comment by Motorhead1991** [comment]
Setting it to exynos7 shouldn't hurt anything but it's  easy enough to change.

As for the header, gralloc and libhwc (I think) both needed it.

**Comment by bmc08gt** [comment]
Other hardware repos check explicitly for exynos5 (iirc), and it would be
silly to set the platform to something it's not being built as by the OEM.

**Comment by Motorhead1991** [comment]
Alright, easy enough. I'll make some backend changes to my ROM source to support different slsi variants. I initially set it due to a multiple definition error I got while compiling.

**Comment by bmc08gt** [comment]
Why not just use CM's updated exynos repos and support in framework? This
repo(and my others) are drop in with CM.

**Comment by bmc08gt** [comment]
I brought in the header separately. Thanks :) https://github.com/bmc08gt/android_hardware_samsung_slsi-cm_exynos7420/commit/143b39469d04e1a192c4485e841a7d74cce5ec41

**Pull request closed without merging**
